### ISSUE TITLE
这个仓库的性质

### ISSUE THREAD

**Issue by hosiet** [ustclug/documentations#1]
- 是否意味着放弃在 dokuwiki 记录内容的做法？
- 仓库是否公开可见？
- 仓库是否存放敏感数据（如特定维护密码）？

**Comment by zhsj** [comment]
现在来看，这个repo会存放维护文档，我觉得还是不公开比较好。虽然可以避免密码之类的，但把一些基础架构之类的暴露了，总觉得我们还没达到可以公开这些的水准。

**Comment by gaoyifan** [comment]
我觉得维护文档可以公开，其实我们基础设施的安全性还是不错的，密码应通过其他途径共享。

**Comment by gaoyifan** [comment]
目前，绝大多数的内部服务都运行在内网中，如：LDAP、salt、docker resgistry

然而，外部主机接入内网只有两种方式：
- 物理接触东图交换机
- 连接LUGI VPN

可能最大的危险来自于：利用服务本身的漏洞，拿到某台机器的shell，然后进入内网。

但即便进入了内网，内网也并非不设防，每台仍然有严格的安全认证。

**Comment by zhsj** [comment]
利用软件漏洞入侵的情况好像也没发生过，以往的入侵都是某个管理员的密码/秘钥泄露，倒不是说管理员本身缺乏安全意识，但遇到APT攻击，我们的水平一般也很难防御。

**Comment by gaoyifan** [comment]
上个月刚发生过：boj的博客光荣中招->邮件配额用尽
